### ISSUE TITLE
Some videos in the training dataset are corrupted.

### ISSUE THREAD

**Issue by purenightmare** [kv2000/ASH#3]
Excellent work! 
I downloaded the dataset you provided a few days ago and found that in Subject0056, the videos numbered 029 and onwards in training/foregroundSegmentation cannot be opened properly. Is there an issue with the data?

**Comment by kv2000** [comment]
Hi, thank you so much for your interest in our work and for raising this issue.

The ***foreground segmentation*** for Subject 0056, starting from camera 29, crashes, (the RGB video seems to be fine from my side) .

Therefore, I made a temporary link on the download page pointing to the ***foreground  segmentation***, named as "Subject0056_training_foregroundSegmentation.zip".

We will update the data in the original link next week when the Admin is back..

**Comment by kv2000** [comment]
Data updated
